version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - tusur-hackathon-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tusur-hackathon-db:5432/tusur-hackathon-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  tusur-hackathon-db:
    container_name: tusur-hackathon-db
    image: 'postgres:13.1-alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tusur-hackathon-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre
